import { NextResponse } from 'next/server';
import { Resend } from 'resend';

const resend = new Resend(process.env.RESEND_API_KEY);

export async function POST(req: Request) {
  try {
    const { toEmail, subject, body } = await req.json();

    if (!toEmail || !subject || !body) {
      return NextResponse.json({ error: 'Missing required fields' }, { status: 400 });
    }

    const { data, error } = await resend.emails.send({
      from: 'PharmaVerify NG <onboarding@resend.dev>',
      to: [toEmail],
      subject: subject,
      html: `
        <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
          <h3 style="color: #d32f2f;">PharmaVerify NG Enforcement Alert</h3>
          <div style="white-space: pre-wrap; padding: 15px; background: #f9f9f9; border-left: 4px solid #d32f2f;">
            ${body}
          </div>
          <p style="font-size: 12px; color: #777; margin-top: 20px;">
            This is an automated regulatory dispatch generated by the PharmaVerify AI Engine.
          </p>
        </div>
      `,
    });

    if (error) {
      console.error('[Resend SDK Error]:', error);
      return NextResponse.json({ error: error.message }, { status: 400 });
    }

    return NextResponse.json({ success: true, data }, { status: 200 });

  } catch (err: any) {
    console.error('[Email Dispatch Error]:', err);
    return NextResponse.json({ error: 'Failed to dispatch email', details: err.message }, { status: 500 });
  }
}